/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.klaw.game.gui;

import com.klaw.game.BinaryEcuation;
import com.klaw.game.Match;
import com.klaw.game.MultEcuation;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Black
 */
public final class MultGui extends javax.swing.JFrame {

    private JFrame frame;
    private Match match;
    private MultEcuation ecuation;
    private final int num = 1;

    //<editor-fold defaultstate="collapsed" desc=" Metodos Auxiliares ">
    /**
     * Creates new form MultGui
     */
    public MultGui() {
        initComponents();
        match = new Match(BinaryEcuation.Operator.MULT, Match.Dificulty.HARD);
        postLoadGui(num);
    }

    /**
     *
     * @param num
     */
    public void postLoadGui(int num) {
        match.initMatch(num);
        ecuation = (MultEcuation) match.next();
        jtLeftOperand.setText(String.valueOf(ecuation.getLeftOperand()));
        jtRightOperand.setText(String.valueOf(ecuation.getRightOperand()));
        bloquearJTextField();
    }

    /**
     * Bloquea los jTextField
     */
    private void bloquearJTextField() {
        jtLeftOperand.enable(false);
        jtRightOperand.enable(false);
        jtEquals.enable(false);
        jtMult.enable(false);

    }

    /**
     * Metodo para hacer de nuevo la multiplicacion
     *
     * @param num
     */
    public void resetMult(int num) {
        match = new Match(BinaryEcuation.Operator.MULT, Match.Dificulty.HARD);
        match.initMatch(num);
        ecuation = (MultEcuation) match.next();
        jtLeftOperand.setText(String.valueOf(ecuation.getLeftOperand()));
        jtRightOperand.setText(String.valueOf(ecuation.getRightOperand()));
    }

    /**
     * Mensajes de salida y manejo de error
     */
    public void checkMult() {
        try {

            if (Integer.parseInt(jtResult.getText()) == ecuation.getResult()) {
                JOptionPane.showMessageDialog(frame,
                        "Correcto!.",
                        "Comprobacion",
                        JOptionPane.PLAIN_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(frame,
                        "Incorrecto!.",
                        "Comprobacion",
                        JOptionPane.PLAIN_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(frame,
                    "Campo vacio",
                    "Error",
                    JOptionPane.PLAIN_MESSAGE);
        }
    }

    /**
     *
     * Metodo de salida de programa
     */
    private void exitProgram() {
        try {
            JOptionPane.showMessageDialog(frame,
                    "Cerrando Aplicacion, espere un momento",
                    "Saliendo",
                    JOptionPane.PLAIN_MESSAGE);
            Thread.sleep(500);
            System.exit(0);

        } catch (InterruptedException ex) {
            Logger.getLogger(MultGui.class.getName()).
                    log(Level.SEVERE, null, ex);
        }

    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbComprobar = new javax.swing.JButton();
        jtLeftOperand = new javax.swing.JTextField();
        jtMult = new javax.swing.JTextField();
        jtRightOperand = new javax.swing.JTextField();
        jtResult = new javax.swing.JTextField();
        jtEquals = new javax.swing.JTextField();
        jbReset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 21, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 21, -1, -1));

        jbComprobar.setText("Comprobar");
        jbComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComprobarActionPerformed(evt);
            }
        });
        getContentPane().add(jbComprobar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jtLeftOperand.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jtLeftOperand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, -1));

        jtMult.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtMult.setText("X");
        getContentPane().add(jtMult, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 21, -1, -1));

        jtRightOperand.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jtRightOperand, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 21, 37, -1));

        jtResult.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getContentPane().add(jtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 21, 55, -1));

        jtEquals.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jtEquals.setText("=");
        getContentPane().add(jtEquals, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 21, 38, -1));

        jbReset.setText("Reiniciar");
        jbReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComprobarActionPerformed
        checkMult();

    }//GEN-LAST:event_jbComprobarActionPerformed

    private void jbResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbResetActionPerformed
        resetMult(num);
    }//GEN-LAST:event_jbResetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        exitProgram();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            MultGui myGui = new MultGui();
            myGui.setVisible(true);
            myGui.setDefaultCloseOperation(0);
            myGui.setDefaultCloseOperation(MultGui.DO_NOTHING_ON_CLOSE);
            myGui.setTitle("Proyecto 1");
            myGui.setLocation(700, 200);
            myGui.setResizable(false);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbComprobar;
    private javax.swing.JButton jbReset;
    private javax.swing.JTextField jtEquals;
    private javax.swing.JTextField jtLeftOperand;
    private javax.swing.JTextField jtMult;
    private javax.swing.JTextField jtResult;
    private javax.swing.JTextField jtRightOperand;
    // End of variables declaration//GEN-END:variables
}
